# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
apt_packages:
    - libv8-dev

r_github_packages:
  - r-hub/crandb

after_success:
  - Rscript -e 'covr::codecov()'

matrix:
  include:
    - os: linux
      r: release
      before_deploy: Rscript -e 'install.packages("pkgdown");remotes::install_github("ropensci/rotemplate")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
    - os: linux
      r: oldrel

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
